[package]
name = "pinned-init"
version = "0.0.0"
edition = "2021"

authors = ["y86-dev"]
license = "MIT OR Apache-2.0"
description = "Library to facilitate safe pinned initialization"
readme = "README.md"

repository = "https://github.com/y86-dev/pinned-init"
keywords = ["safe", "pin", "init", "no-std", "rust-patterns"]
categories = ["no-std", "rust-patterns", "embedded"]

[dependencies]
pin-project = "^1.0.0"
pinned-init-macro = { version = "=0.0.0", path = "pinned-init-macro" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []
