[package]
name = "pinned-init"
version = "0.0.2"
edition = "2021"

authors = ["y86-dev"]
license = "MIT OR Apache-2.0"
description = "Library to facilitate safe pinned initialization"
readme = "README.md"

documentation = "https://docs.rs/pinned-init"
repository = "https://github.com/y86-dev/pinned-init"
keywords = ["safe", "pin", "init", "no-std", "rust-patterns"]
categories = ["no-std", "rust-patterns", "embedded"]

[dependencies]
pinned-init-macro = { path = "./pinned-init-macro" }

[features]
default = ["std"]
std = []
alloc = []

[dev-dependencies]
libc = "0.2"
